import { MarketCandle, InstrumentConfig, RiskSettings } from '../types';
import {
  BacktestConfig,
  BacktestReport,
  BacktestTrade,
  StrategyFilter,
} from '../types/backtest';
import { validateHistoricalDataset } from './dataValidator';
import { simulateTradeOutcome, PendingTradeSetup } from './tradeSimulator';
import {
  calculatePerformanceMetrics,
  generateEquityCurve,
  generateConfidenceBuckets,
  generateRRBuckets,
  generateStrategyBreakdown,
  generateRegimeBreakdown,
  generateAssetBreakdown,
  generateTimeframeBreakdown,
  computePerformerHighlights,
  runMonteCarloSimulation,
} from './metricsCalculator';
import { generateSignalDecision } from '../signals/decisionEngine';

/**
 * Executes a strictly sequential, event-based historical backtest.
 *
 * Guaranteed Invariants:
 * 1. Zero Look-Ahead Bias: At historical candle N, only candles <= N are passed to the engine.
 * 2. Closed-Candle Confirmation: Signal confirmed on close of candle N; trade executes on open of candle N+1.
 * 3. Exact SL/TP: Stops and targets generated by the strategy engine are not retroactively moved.
 * 4. Configurable Same-Candle Conflict Resolution (Default: Conservative LOSS).
 * 5. One Position Per Symbol default enforcement.
 */
export function runEventBasedBacktest(
  rawCandles: MarketCandle[],
  config: BacktestConfig,
  instrument: InstrumentConfig
): BacktestReport {
  const startTime = Date.now();

  // 1. Data Validation & Cleaning
  const { cleanCandles, report: dataQuality } = validateHistoricalDataset(
    rawCandles,
    config.timeframe
  );

  const firstCandleTs = cleanCandles.length > 0 ? (cleanCandles[0].time || cleanCandles[0].timestamp || 0) : 0;
  const lastCandleTs = cleanCandles.length > 0 ? (cleanCandles[cleanCandles.length - 1].time || cleanCandles[cleanCandles.length - 1].timestamp || 0) : 0;

  const defaultDatasetInfo = {
    symbol: instrument.symbol,
    timeframe: config.timeframe,
    totalCandles: cleanCandles.length,
    startDate: firstCandleTs ? new Date(firstCandleTs).toISOString() : '',
    endDate: lastCandleTs ? new Date(lastCandleTs).toISOString() : '',
    inSampleCount: 0,
    outOfSampleCount: 0,
    source: 'Market Data Stream',
    dataQuality,
  };

  if (!dataQuality.isValid || cleanCandles.length < 30) {
    const emptyMetrics = calculatePerformanceMetrics([]);
    return {
      id: `BT-${Date.now().toString(36).toUpperCase()}`,
      timestamp: Date.now(),
      config,
      datasetInfo: defaultDatasetInfo,
      overallMetrics: emptyMetrics,
      inSampleMetrics: emptyMetrics,
      outOfSampleMetrics: emptyMetrics,
      equityCurve: [],
      trades: [],
      strategyBreakdown: [],
      confidenceBuckets: [],
      rrBuckets: [],
      regimeBreakdown: [],
      assetBreakdown: [],
      timeframeBreakdown: [],
      executionSummary: {
        durationMs: Date.now() - startTime,
        evaluatedCandles: 0,
        generatedSignals: 0,
        executedTrades: 0,
        skippedOverlapping: 0,
        skippedLowConfidence: 0,
        skippedLowRR: 0,
      },
    };
  }

  // 2. In-Sample (70%) vs Out-of-Sample (30%) Split Index
  const totalCount = cleanCandles.length;
  const inSampleRatio = config.inSampleRatio || 0.7;
  const splitIndex = Math.floor(totalCount * inSampleRatio);

  defaultDatasetInfo.inSampleCount = splitIndex;
  defaultDatasetInfo.outOfSampleCount = totalCount - splitIndex;

  const warmup = Math.max(25, config.warmupPeriod || 35);
  const executedTrades: BacktestTrade[] = [];

  let evaluatedCandles = 0;
  let generatedSignals = 0;
  let skippedOverlapping = 0;
  let skippedLowConfidence = 0;
  let skippedLowRR = 0;

  // Track active positions to enforce position models (e.g. ONE_POSITION_PER_SYMBOL)
  let activePositionUntilBarIndex = -1;

  const riskSettings: RiskSettings = {
    maxRiskPerTradePercent: 1.0,
    minRiskReward: config.minRiskReward || 1.5,
    maxSimultaneousSignals: 4,
    maxDailySignals: 10,
    maxConsecutiveLosses: 3,
    maxDailyDrawdownPercent: 3.0,
    minConfidenceRequired: config.minConfidence || 60,
  };

  // 3. Chronological Event Loop
  for (let N = warmup; N < cleanCandles.length - 1; N++) {
    evaluatedCandles++;

    const isCurrentInSample = N < splitIndex;
    const sampleType = isCurrentInSample ? 'IN_SAMPLE' : 'OUT_OF_SAMPLE';

    // Sample Mode Filter (skip if user chose only In-Sample or Out-of-Sample)
    if (config.sampleMode === 'IN_SAMPLE' && !isCurrentInSample) {
      continue;
    }
    if (config.sampleMode === 'OUT_OF_SAMPLE' && isCurrentInSample) {
      continue;
    }

    // Check One-Position-Per-Symbol Constraint
    if (config.positionModel === 'ONE_POSITION_PER_SYMBOL' && N <= activePositionUntilBarIndex) {
      // Position is currently open; skip opening simultaneous trade
      continue;
    }

    // EXTRACT STRICT HISTORICAL SLICE: ONLY candles <= N
    const historicalSlice = cleanCandles.slice(0, N + 1);

    // Evaluate Strategy Engine at Candle N Close
    const signal = generateSignalDecision(
      instrument,
      config.tradeType,
      historicalSlice,
      historicalSlice,
      riskSettings
    );

    if (signal.direction === 'WAIT') {
      continue;
    }

    generatedSignals++;

    // Guard: Confidence Check
    if (signal.confidenceScore < config.minConfidence) {
      skippedLowConfidence++;
      continue;
    }

    // Guard: Risk/Reward Check
    if (signal.riskReward < config.minRiskReward) {
      skippedLowRR++;
      continue;
    }

    // Strategy Filter Matching
    let primaryStrategy = 'Trend-Following';
    const breakdown = signal.strategyBreakdown;
    if (breakdown.breakout) primaryStrategy = 'Breakout Analysis';
    else if (breakdown.pullback) primaryStrategy = 'Pullback Analysis';
    else if (breakdown.liquiditySweep) primaryStrategy = 'Liquidity Sweep';
    else if (breakdown.supportResistance) primaryStrategy = 'Support & Resistance';
    else if (breakdown.trendFollowing) primaryStrategy = 'Trend-Following';

    if (config.strategyFilter !== 'ALL') {
      const match = matchesStrategyFilter(config.strategyFilter, breakdown);
      if (!match) {
        continue;
      }
    }

    // Active position overlap check
    if (config.positionModel === 'ONE_POSITION_PER_SYMBOL' && N <= activePositionUntilBarIndex) {
      skippedOverlapping++;
      continue;
    }

    const supportingStrategies: string[] = [];
    if (breakdown.breakout) supportingStrategies.push('Breakout');
    if (breakdown.pullback) supportingStrategies.push('Pullback');
    if (breakdown.trendFollowing) supportingStrategies.push('Trend-Following');
    if (breakdown.liquiditySweep) supportingStrategies.push('Liquidity Sweep');
    if (breakdown.supportResistance) supportingStrategies.push('S/R Bounce');

    const sigTime = cleanCandles[N].time || cleanCandles[N].timestamp || 0;
    const sigTimeISO = cleanCandles[N].datetime || new Date(sigTime).toISOString();

    const setup: PendingTradeSetup = {
      id: `TRD-${instrument.symbol.replace(/[/_ -]/g, '')}-${N}-${Math.floor(Math.random() * 1000)}`,
      symbol: instrument.symbol,
      strategy: primaryStrategy,
      direction: signal.direction,
      signalBarIndex: N,
      signalTime: sigTime,
      signalTimeISO: sigTimeISO,
      calculatedEntry: signal.suggestedEntry,
      stopLoss: signal.stopLoss,
      takeProfit: signal.takeProfit1,
      takeProfit2: signal.takeProfit2,
      confidenceScore: signal.confidenceScore,
      riskReward: signal.riskReward,
      marketRegime: signal.conditionsDetected?.[0] || 'TRENDING_BULLISH',
      volatilityState: signal.strategyBreakdown?.volatility ? 'NORMAL' : 'COMPRESSED',
      supportingStrategies,
      sampleType,
    };

    // Forward Trade Simulation
    const completedTrade = simulateTradeOutcome(setup, cleanCandles, config);

    if (completedTrade) {
      executedTrades.push(completedTrade);
      activePositionUntilBarIndex = completedTrade.exitBarIndex;
    }
  }

  // 4. Performance Analytics & Segmentations
  const overallMetrics = calculatePerformanceMetrics(executedTrades, skippedOverlapping);

  const inSampleTrades = executedTrades.filter((t) => t.sampleType === 'IN_SAMPLE');
  const outOfSampleTrades = executedTrades.filter((t) => t.sampleType === 'OUT_OF_SAMPLE');

  const inSampleMetrics = calculatePerformanceMetrics(inSampleTrades);
  const outOfSampleMetrics = calculatePerformanceMetrics(outOfSampleTrades);

  const equityCurve = generateEquityCurve(executedTrades);
  const strategyBreakdown = generateStrategyBreakdown(executedTrades);
  const confidenceBuckets = generateConfidenceBuckets(executedTrades);
  const rrBuckets = generateRRBuckets(executedTrades);
  const regimeBreakdown = generateRegimeBreakdown(executedTrades);
  const assetBreakdown = generateAssetBreakdown(executedTrades);
  const timeframeBreakdown = generateTimeframeBreakdown(executedTrades, config.timeframe);
  const performers = computePerformerHighlights(assetBreakdown, strategyBreakdown, timeframeBreakdown);
  const monteCarlo = executedTrades.length > 0 ? runMonteCarloSimulation(executedTrades, 1000, 42) : undefined;

  const durationMs = Date.now() - startTime;

  return {
    id: `BT-${Date.now().toString(36).toUpperCase()}`,
    timestamp: Date.now(),
    config,
    datasetInfo: defaultDatasetInfo,
    overallMetrics,
    inSampleMetrics,
    outOfSampleMetrics,
    equityCurve,
    trades: executedTrades,
    strategyBreakdown,
    confidenceBuckets,
    rrBuckets,
    regimeBreakdown,
    assetBreakdown,
    timeframeBreakdown,
    bestPerformingAsset: performers.bestPerformingAsset,
    worstPerformingAsset: performers.worstPerformingAsset,
    bestPerformingStrategy: performers.bestPerformingStrategy,
    worstPerformingStrategy: performers.worstPerformingStrategy,
    bestPerformingTimeframe: performers.bestPerformingTimeframe,
    worstPerformingTimeframe: performers.worstPerformingTimeframe,
    monteCarlo,
    executionSummary: {
      durationMs,
      evaluatedCandles,
      generatedSignals,
      executedTrades: executedTrades.length,
      skippedOverlapping,
      skippedLowConfidence,
      skippedLowRR,
    },
  };
}

/**
 * Runs backtest sequentially across multiple instruments and aggregates results.
 */
export function runMultiAssetBacktest(
  assetDatasets: { instrument: InstrumentConfig; candles: MarketCandle[] }[],
  config: BacktestConfig
): import('../types/backtest').MultiAssetBacktestReport {
  const assetReports: Record<string, BacktestReport | { error: string; symbol: string }> = {};
  const allExecutedTrades: BacktestTrade[] = [];

  for (const { instrument, candles } of assetDatasets) {
    try {
      if (!candles || candles.length < (config.warmupPeriod || 30) + 5) {
        assetReports[instrument.symbol] = {
          error: 'INSUFFICIENT_HISTORICAL_DATA',
          symbol: instrument.symbol,
        };
        continue;
      }

      const report = runEventBasedBacktest(
        candles,
        { ...config, symbol: instrument.symbol },
        instrument
      );
      assetReports[instrument.symbol] = report;
      allExecutedTrades.push(...report.trades);
    } catch (err: any) {
      assetReports[instrument.symbol] = {
        error: err.message || 'Backtest execution error',
        symbol: instrument.symbol,
      };
    }
  }

  // Sort combined trades chronologically
  allExecutedTrades.sort((a, b) => a.entryTime - b.entryTime);
  const overallMetrics = calculatePerformanceMetrics(allExecutedTrades);
  const monteCarlo = overallMetrics.totalTrades > 0
    ? runMonteCarloSimulation(allExecutedTrades, 1000, 42)
    : undefined;

  const inSampleTrades = allExecutedTrades.filter((t) => t.sampleType === 'IN_SAMPLE');
  const outOfSampleTrades = allExecutedTrades.filter((t) => t.sampleType === 'OUT_OF_SAMPLE');

  const totalCandles = assetDatasets.reduce((acc, d) => acc + (d.candles?.length || 0), 0);

  const strategyBreakdown = generateStrategyBreakdown(allExecutedTrades);
  const confidenceBuckets = generateConfidenceBuckets(allExecutedTrades);
  const rrBuckets = generateRRBuckets(allExecutedTrades);
  const regimeBreakdown = generateRegimeBreakdown(allExecutedTrades);
  const assetBreakdown = generateAssetBreakdown(allExecutedTrades);
  const timeframeBreakdown = generateTimeframeBreakdown(allExecutedTrades, config.timeframe);
  const performers = computePerformerHighlights(assetBreakdown, strategyBreakdown, timeframeBreakdown);

  const portfolioReport: BacktestReport = {
    id: `PORTFOLIO-BT-${Date.now().toString(36).toUpperCase()}`,
    timestamp: Date.now(),
    config,
    datasetInfo: {
      symbol: 'ALL_PORTFOLIO',
      timeframe: config.timeframe,
      totalCandles,
      startDate: new Date(allExecutedTrades[0]?.entryTime || Date.now()).toISOString(),
      endDate: new Date(allExecutedTrades[allExecutedTrades.length - 1]?.exitTime || Date.now()).toISOString(),
      inSampleCount: inSampleTrades.length,
      outOfSampleCount: outOfSampleTrades.length,
      source: 'MULTI_ASSET_HISTORICAL_ARCHIVES',
      dataQuality: {
        isValid: true,
        totalCandles,
        duplicateCount: 0,
        outOfOrderCount: 0,
        zeroOrNaNCandles: 0,
        invalidGeometryCount: 0,
        gapsDetected: 0,
        warnings: [],
        errors: [],
      },
    },
    overallMetrics,
    inSampleMetrics: calculatePerformanceMetrics(inSampleTrades),
    outOfSampleMetrics: calculatePerformanceMetrics(outOfSampleTrades),
    equityCurve: generateEquityCurve(allExecutedTrades),
    trades: allExecutedTrades,
    strategyBreakdown,
    confidenceBuckets,
    rrBuckets,
    regimeBreakdown,
    assetBreakdown,
    timeframeBreakdown,
    bestPerformingAsset: performers.bestPerformingAsset,
    worstPerformingAsset: performers.worstPerformingAsset,
    bestPerformingStrategy: performers.bestPerformingStrategy,
    worstPerformingStrategy: performers.worstPerformingStrategy,
    bestPerformingTimeframe: performers.bestPerformingTimeframe,
    worstPerformingTimeframe: performers.worstPerformingTimeframe,
    monteCarlo,
    executionSummary: {
      durationMs: 0,
      evaluatedCandles: totalCandles,
      generatedSignals: allExecutedTrades.length,
      executedTrades: allExecutedTrades.length,
      skippedOverlapping: 0,
      skippedLowConfidence: 0,
      skippedLowRR: 0,
    },
  };

  return {
    id: `MULTI-BT-${Date.now().toString(36).toUpperCase()}`,
    timestamp: Date.now(),
    config,
    overallMetrics,
    portfolioReport,
    assetReports,
    monteCarlo,
  };
}

function matchesStrategyFilter(filter: StrategyFilter, breakdown: any): boolean {
  switch (filter) {
    case 'BREAKOUT':
      return !!breakdown.breakout;
    case 'PULLBACK':
      return !!breakdown.pullback;
    case 'TREND_FOLLOWING':
      return !!breakdown.trendFollowing;
    case 'LIQUIDITY_SWEEP':
      return !!breakdown.liquiditySweep;
    case 'SUPPORT_RESISTANCE':
      return !!breakdown.supportResistance;
    default:
      return true;
  }
}

